 **Assignment Day 3 | 11th November 2020**
 
**Name : mukesh kumar mahto**

***Email: mukesh.7755@gmail.com***

 **Questions 1:**
 
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [8]:
 
import numpy as np 
arr = np.arange(2, 50, 2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


 **Questions 2:**

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [25]:
import numpy
# number of elements 
 
n = 5
 
  
# Below line read inputs from user using map() function  
 
a = list(map(int,input("\nEnter the numbers for 1st list: ").strip().split()))[:n] 
 
b = list(map(int,input("\nEnter the numbers for 2nd list : ").strip().split()))[:n]
c = a + b 
 
c.sort() 
 
# converting list to array
 
arr1 = numpy.array(a)
# converting list to array
 
arr2 = numpy.array(b)
# displaying list
print ("first List : ", a)
 
# displaying array
print ("first Array: ", arr1)
# displaying list
print ("second List: ", b)
 
# displaying array
print ("second Array: ", arr2)
d = numpy.concatenate((arr1, arr2), axis = 0)
print(d)
print("after concatenation of two array: ", d)
 
print("after sorted of array: ")
print(c)


Enter the numbers for 1st list: 3 44 12

Enter the numbers for 2nd list : 10 7 2
first List :  [3, 44, 12]
first Array:  [ 3 44 12]
second List:  [10, 7, 2]
second Array:  [10  7  2]
[ 3 44 12 10  7  2]
after concatenation of two array:  [ 3 44 12 10  7  2]
after sorted of array: 
[2, 3, 7, 10, 12, 44]


**Questions 3:"**
 
Write a code snippet to find the dimensions of a ndarray and its size.

In [26]:
 
# Python program to demonstrate 
# basic array characteristics
import numpy as np
 
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


**Questions 4:**
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [ ]:
 import numpy as np 
x = np.array(([1,2],[3,4])) 

print 'Array x:' 
print x 
print '\n'  
y = np.expand_dims(x, axis = 0) 

print 'Array y:' 
print y 
print '\n'

print 'The shape of X and Y array:' 
print x.shape, y.shape 
print '\n'  
# insert axis at position 1 
y = np.expand_dims(x, axis = 1) 

print 'Array Y after inserting axis at position 1:' 
print y 
print '\n'  

print 'x.ndim and y.ndim:' 
print x.ndim,y.ndim 
print '\n'  

print 'x.shape and y.shape:' 
print x.shape, y.shape

**Questions 5:**
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [29]:
 
 
import numpy as np 
 
  
 
a = np.array([[1, 2], 
 
              [3, 4]]) 
 
  
 
b = np.array([[5, 6], 
 
              [7, 8]]) 
 
  
# vertical stacking 
 
 print("Array 1:\n", a)
print("Array 2:\n", b)
print("Vertical stacking:\n", np.vstack((a, b))) 
 
  
# horizontal stacking 
 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Array 1:
 [[1 2]
 [3 4]]
Array 2:
 [[5 6]
 [7 8]]
Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


**Questions 6:**
How to get unique items and counts of unique items?

In [36]:
 
 
input_list = [1, 2, 2, 5, 8, 4, 4, 8] 
 
  
# converting our list to set 
 
new_set = set(input_list) 
 
print("No of unique items in the list are:", len(new_set))
print(new_set)

No of unique items in the list are: 5
{1, 2, 4, 5, 8}
